### ISSUE TITLE
Metaprotocol Comments & Reactions - feature list

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/joystream#3322]
This issue lists the Metaprotocol based implementation of basic features related to comment & reaction.

For each action/feature listed here I have described different pieces involved from start to end (i.e. from calling the `*_remark` extrinsic, to processing the message in mappings, and then updating the QN state):

`Message`: Protocol buffers message used for given action, 
`Event`: The event emitted (containing serialized protobuf message) by the `*_remark` extrinsic,
`Validations`: Validations performed on the message in mappings before making it part of Query Node state,

## Schema
```graphql
enum ReactionOptions {
  CANCEL
  LIKE
  UNLIKE
}

type VideoReaction @entity {
  "Unique identifier"
  id: ID!

  "The Reaction"
  reaction: ReactionOptions!

  "The member that reacted"
  member: Membership!

  "The video that has been reacted to"
  video: Video!
}

type CommentReaction @entity {
  "Unique identifier"
  id: ID!

  "The Reaction"
  reaction: ReactionOptions!

  "The member that reacted"
  member: Membership!

  "The comment that has been reacted to"
  comment: Comment!
}

type Comment @entity {
  "Unique identifier"
  id: ID!

  "Author of the video comment"
  author: Membership!

  "Comment text"
  text: String @fulltext(query: "commentText")

  "Video the comment was added to"
  video: Video!

  "True if the comment is visible; moderators can set this flag"
  isVisible: Boolean!

  "List of all reactions to the comment"
  reactions: [CommentReaction!] @derivedFrom(field: "comment")

  "A (parent) comment that this comment replies to (if any)"
  parentCommentId: Comment
}
```

#### Message 
```proto
message ReactVideo {
  required uint64 video_id = 1;
  enum Reaction {
    CANCEL = 0;
    LIKE = 1;
    UNLIKE = 2;
   }
   required Reaction reaction = 2;
}
```
#### Event
`MemberRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment section is enabled_

### Message 
Same message used to react a video, with enum field set to `CANCEL`
#### Event
`MemberRemarked`

#### Validations
- _Ensure video exists_ 
- _Ensure comment section is enabled_
- _Ensure member reacted previously_

#### Message 
```proto
message ReactComment {
  required uint64 comment_id = 1;
  enum Reaction {
    CANCEL = 0;
    LIKE = 1;
    UNLIKE = 2;
  }
  required Reaction reaction = 2;
}
```
#### Event
`MemberRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment exists_
- _Ensure comment section is enabled_

#### Message 
Same message used to react a comment, with enum field set to `CANCEL` 
#### Event
`MemberRemarked`

#### Validations
- _Ensure video exists_ 
- _Ensure comment exists_
- _Ensure comment section is enabled_
- _Ensure member reacted previously_

#### Message 
```proto
message CreateComment {
  required uint64 video_id = 1;
  optional uint64 parent_comment_id = 2;
  required string body = 3;
}
```
#### Event
`MemberRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment section is enabled_

#### Message 
```proto
message EditComment {
  required uint64 video_id = 1;
  required uint64 comment_id = 2;
  required string new_body = 3;
}
```
#### Event
`MemberRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment exists_
- _Ensure comment section is enabled_
- _Ensure comment is being edited by author_

#### Message 
```proto
message DeleteComment {
  required uint64 video_id = 1;
  required uint64 comment_id = 2;
}
```
#### Event
`MemberRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment exists_
- _Ensure comment section is enabled_
- _Ensure comment is being deleted by author_

#### Message 
```proto
message DeleteCommentModerator {
  required uint64 video_id = 1;
  required uint64 comment_id = 2;
  required string rationale = 3;
}
```
#### Event
`ChannelModeratorRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment exists_
- _Ensure channel owns the video_
- _Ensure comment is under the video_

#### Message 
```proto
message PinComment { 
  required uint64 video_id = 1;
  required uint64 comment_id = 2;
}
```
#### Event
`ChannelOwnerRemarked`

#### Validations 
- _Ensure video exists_ 
- _Ensure comment exists_
- _Ensure channel owns the video_
- _Ensure comment is under the video_

#### Message 
```proto
message EnableOrDisableCommentSection {
  enum Option {
    ENABLE = 0; 
    DISABLE = 1; 
  }
  required Option option = 2;
}
```
#### Event
`ChannelOwnerRemarked`

#### Validations 
- _None_

#### Message 
```proto
message BanMemberFromChannel { 
  required uint64 member_id = 1;
  enum Option {
    BAN = 0;
    UNBAN = 1;
  }
  required Option option = 2;
}
```
#### Event
`ChannelOwnerRemarked`

#### Validations 
- _Ensure member exists_

**Comment by bedeho** [comment]
First off, this was a great summary, really great job.

# Schemas

Can you please add input schema and resulting API schema to the issue?

# Question

I am seeing that we are using `MemberRemarked`, but I wonder, should we instead a have acontent directory related extrinsic here? It will perhaps make it easier to write mappings that all deal with one subsystem at a time, while in the membershipsystem, everything will leak in all at once (form, content, bounty, ...).

Would be great to get your point of view on this.

# React to Video

- Don't you need to check that Member has not already reacted in the same way to this vide?
You should cross ref with @kdembler  here on what they are expecting.
- Don't you need to check that the vidoe entity is indeed a video? remember that for example playlists, audio tracks, they will all be implemented as the on-chain entity `Video`. We are going to rename it to `Content` or something, to make this more clear. Anyway, should comments exist for all types? I could see a case for just doing that to begin with also. This means we can get a comment section on the dedicated playlist page we are building.
- Is reacting restricted together with comments? I am not sure about that. This may not be what Atlas design team is epecting.

# Unreact to Video

Similar points to `React to Video`

# React to Comment

- Here you are checking that both video and comment exists, but if we assume comments will automatically get removed when the video gets deleted, then perhaps the video check is redundant.
- To faciliate the sort of effective deletion I just mentioned in the prior point, each comment will, at least in the database, have the video ID it belongs to as a field, the parent comment would not be sufficient.
- Is the identifier of a comment just a standalone value? or does it include the video?

# Unreact to Comment

Similar.

# Create Comment

Don't you need to check that the parent comment exists?

# Edit Comment

Looks good, with same question about video existance.

# Delete Comment (by Moderator)

I presume you here just delete the one comment, all child comments remain, and their parent id foreign keys will dangle? I think this is fine, but I guess the UI design has to handle this (@kdembler), and it also means my suggestion to bind all comments directly ot the video as I mention above is really not even optional.

# Ban Member from Channel

- You don't seem to check this banning permission in any other message.
- What about unbanning?

# Video Deletion

I think you need to hook into this event and delete all comments&reactions for a video when the video is deleted.

**Comment by zeeshanakram3** [comment]
I have updated the issue to add basic schema of Comment and Reaction entities (excluding event-related entities). And I think most of the question would be answered looking at the Schema

# React to Video
> Don't you need to check that Member has not already reacted in the same way to this vide?

There are two scenarios if the member has already reacted to the video and they react again. I handled them the following way:
1. New reaction is different from the previous reaction `->` Change reaction to the new one
2. New reaction is the same as the previous one `->` No side effect

Anyways, will cross ref this.

> Don't you need to check that the vidoe entity is indeed a video? remember that for example playlists, audio tracks, they will all be implemented as the on-chain entity Video. 

Wasn't aware of that, Will include that check too

> Is reacting restricted together with comments? I am not sure about that. This may not be what Atlas design team is expecting.

Yes. Though they can be separated (if reacting restriction is needed), e.g. One message to Enable/Disable comments, another to  Enable/Disable reactions.

# React to Comment
>  then perhaps the video check is redundant.

Yes, you are right this check is redundant 

> To faciliate the sort of effective deletion I just mentioned in the prior point, each comment will, at least in the database, have the video ID it belongs to as a field, the parent comment would not be sufficient.

The comment has both, a required `video` field, and a nullable `parentCommentId` field 

> Is the identifier of a comment just a standalone value? or does it include the video?

It is a standalone identifier.

# Create Comment
> Don't you need to check that the parent comment exists?

In the protobuf message, `parent_comment_id` is an optional field, so this message would be used to create both the (root level) comments and replies (to other comments). If `parent_comment_id` is present in the serialized message then yes, its existence would be checked and `parentCommentId` field of Comment entity would be set to the parent comment,  otherwise `parentCommentId` field of Comment would be set to null (means the comment is root level comment) 

# Delete Comment (by Moderator)
>I presume you here just delete the one comment, all child comments remain,

yes

> and their parent id foreign keys will dangle?
No, the comment won't actually be deleted from DB, comment entity has is `isVisible` flag which would be set to false, and based on that UI can show deleted on that content, One more thing, the comment text would be cleared from comment record and would be set as empty string


# Ban Member from Channel
> You don't seem to check this banning permission in any other message. 

Are you asking about checking member existence that will be banned? If yes, then we don't need to, `*_remark` extrinsic would do that

> What about unbanning?

I have updated the protobuf message

**Comment by zeeshanakram3** [comment]
I have updated the issue to add basic schema of Comment and Reaction entities (excluding event-related entities). And I think most of the question would be answered looking at the Schema. 
For complete schemas please have a look at these:
https://github.com/zeeshanakram3/joystream/blob/olympia/query-node/schemas/contentEvents.graphql

https://github.com/zeeshanakram3/joystream/blob/30f2651b4405578a44403b9d8e9da4164309f3d4/query-node/schemas/content.graphql#L220

> should we instead a have acontent directory related extrinsic here?

As you mentioned it would be easier to write mappings since `members_MemberRemarked` mapping would be less cluttered, as we won't have a giant `switch/case` statement to find what type serialized message is and then do work accordingly

The downside is having redundant extrinsics in each subsystem, e.g. `content_member_remark`, `bounty_member_remark` that are doing the same work i.e. ensuring valid signature and membership



# React to Video
> Don't you need to check that Member has not already reacted in the same way to this vide?

There are two scenarios if the member has already reacted to the video and they react again. I handled them the following way:
1. New reaction is different from the previous reaction `->` Change reaction to the new one
2. New reaction is the same as the previous one `->` No side effect

Anyways, will cross ref this.

> Don't you need to check that the vidoe entity is indeed a video? remember that for example playlists, audio tracks, they will all be implemented as the on-chain entity Video. 

Wasn't aware of that, Will include that check too

> Is reacting restricted together with comments? I am not sure about that. This may not be what Atlas design team is expecting.

Yes. Though they can be separated (if reacting restriction is needed), e.g. One message to Enable/Disable comments, another to  Enable/Disable reactions.

# React to Comment
>  then perhaps the video check is redundant.

Yes, you are right this check is redundant 

> To faciliate the sort of effective deletion I just mentioned in the prior point, each comment will, at least in the database, have the video ID it belongs to as a field, the parent comment would not be sufficient.

The comment has both, a required `video` field, and a nullable `parentCommentId` field 

> Is the identifier of a comment just a standalone value? or does it include the video?

It is a standalone identifier.

# Create Comment
> Don't you need to check that the parent comment exists?

In the protobuf message, `parent_comment_id` is an optional field, so this message would be used to create both the (root level) comments and replies (to other comments). If `parent_comment_id` is present in the serialized message then yes, its existence would be checked and `parentCommentId` field of Comment entity would be set to the parent comment,  otherwise `parentCommentId` field of Comment would be set to null (means the comment is root level comment) 

# Delete Comment (by Moderator)
>I presume you here just delete the one comment, all child comments remain,

yes

> and their parent id foreign keys will dangle?

No, the comment won't actually be deleted from DB, comment entity has is `isVisible` flag which would be set to false, and based on that UI can show deleted on that content, One more thing, the comment text would be cleared from comment record and would be set as empty string


# Ban Member from Channel
> You don't seem to check this banning permission in any other message. 

Yep, missed that, will add it too.

> What about unbanning?

I have updated the protobuf message 

# Video Deletion
>I think you need to hook into this event and delete all comments&reactions for a video when the video is deleted.

Noted. Here all comments and reactions would be removed from DB, unlike in the case of deleting comments where only the visibility was changed to avoid the problem of dangling parent comment IDs

**Comment by kdembler** [comment]
Thanks for this summary, really easy to digest 👍 

### Messages

1. We assume same reaction set and same reaction logic for both videos and comments. That's not fully compatible with what we're designing for Atlas:
a) We would like to use much more rich reaction set for comments, using emojis, you can see early designs for this [here](https://www.figma.com/file/EzJmuVoYrIEuUZ8VhqEBdH/Video-page%3A-Reactions-%26-Comments?node-id=2029%3A470826). The reaction set has not been finalized yet. Could we use some kind of generic reactions? So without an enum listing possible options, but just some kind of ID that can be transparent to the query node?
b) Because of above, we would like to not restrict user to a single reaction **for comments**. We want our comments section to be very similar to Discord in that regard - you can react with 10 emojis to a single comment if you wish so. Could we remove that validation for comments?
c) Because of above, the current approach for removing a reaction would not work, since the user would need to identify which reaction to remove.

2. To follow up on the comment made by Bedeho, I think that reacting to video should be independent of whether the comment section is enabled. Personally, I would start with reactions to video always enabled and potentially add switch off in the future if desired. @bedeho WDYT?
3. Just to make sure I understand correctly. `ReactComment` includes only `comment_id`, that means that comment IDs are globally unique, yes?
4. If I delete my own comment, would the behaviour be the same as you described above for deletion by moderator? That is, the comment would still be query-able, but just its body would be removed and `isVisible` would be false? Or is the behavour here something else?

### Schema

_Those comments are based on schema in the comment above and [this one](https://github.com/zeeshanakram3/joystream/blob/30f2651b4405578a44403b9d8e9da4164309f3d4/query-node/schemas/content.graphql)_

1. We will need to come up with some clever way of querying reactions. With the current approach, I can just get a list of all the `VideoReaction` for a given video. However, if you think about a popular video with thousands of likes/dislikes, fetching thousands of objects just to display their final count is quite inefficient. I think we will need some kind of counters that can be queried directly to get a status of given reactions. Same goes for comments. Very quick draft of how this could look like, WDYT?
```graphql
type Reaction {
  id: ID!
  count: Int!
}
type Video {
  # ...
  reactions: [Reaction!]!
}
```

2. We would like to know how many replies a given comment has, to show something like `Show X replies` in the UI. Could a counter like this be added to the `Comment` type?

3. `isCommentSectionEnabled` seems to be defined for both `Channel` and `Video`, I guess it's just a typo

### Open questions

1. How do we let users enable/disable the comment section as part of video publishing? Since video details and comment details live in two separate subsystems (on-chain content module and content metaprotocol), first guess would be that you need to run separate extrinsics for those (firstly create a video, secondly notify the metaprotocol that you want to enable comments). This would require 2 separate signatures from the user though, which is non-ideal UX. Not sure how we solve this. One solution would be to let the user emit a remark as part of video create/edit?

2. (🤯 warning) In Atlas we obviously want to show the user whether they have already reacted to the specific video/comment. If they already posted a heart emoji for this awesome comment, they want to get feedback that their reaction is there. How do we achieve that with a stateless backend like the query node? Getting all the reaction events for each comment is not feasible as mentioned above, since there can be quite a lot of those. Only thing that comes to my mind at the moment is a followup to my suggested schema update in the `Schema` section. `comments` query could accept `memberId` argument that would indicate that we want to get info on this specific user's reactions. Then the comment body could contain something like:
```graphql
type Comment {
  # ...
  memberReactions: [ID!]!
}
```
Not even sure if this is even doable in QN, this would be a kind of computed state, based on query arguments. WDYT?

---

It's a bit late as I'm writing this so let me know if something doesn't make sense 😅

**Comment by bedeho** [comment]
> To follow up on the comment made by Bedeho, I think that reacting to video should be independent of whether the comment section is enabled. Personally, I would start with reactions to video always enabled and potentially add switch off in the future if desired.

Sounds totally fine by me ;)

> How do we let users enable/disable the comment section as part of video publishing? Since video details and comment details live in two separate subsystems (on-chain content module and content metaprotocol), first guess would be that you need to run separate extrinsics for those (firstly create a video, secondly notify the metaprotocol that you want to enable comments). This would require 2 separate signatures from the user though, which is non-ideal UX. Not sure how we solve this. One solution would be to let the user emit a remark as part of video create/edit?

There is no problem bundling in a signal in the video creation metadat which has meaning relevant to the comments.

> their reaction is there. How do we achieve that with a stateless backend like the query node?

QN is not stateless, not sure what you mean by that?

>  Getting all the reaction events for each comment is not feasible as mentioned above, since there can be quite a lot of those. 

Where is this claimed?

**Comment by kdembler** [comment]
> There is no problem bundling in a signal in the video creation metadata which has meaning relevant to the comments.

So in this specific case we're talking about enabling/disabling comment section. However, looking at the messages above I think what Zeeshan planned is that comments are enabled/disabled on the channel level? If that's the case then maybe there is no problem, however if we wanted to do it per video, I think we may have an issue. You say that video creation could contain param for enabling/disabling the comment section? Then there would be some custom event required, right? Since the member remark cannot be constructed by the runtime since it doesn't know the protobuf format. On the other hand, user doesn't know the video ID before it gets created, so they cannot construct the message beforehand.

> QN is not stateless, not sure what you mean by that?

Okay, maybe that's wrong wording. What I meant here is that QN is session-less - it doesn't know anything about the user that runs the queries, like a regular backend would. Based on session, returned data could be personalized, for example, to include reactions a given user has submitted. We can't do that so that's why I suggested the solution with `memberId` passed as an argument

> > Getting all the reaction events for each comment is not feasible as mentioned above, since there can be quite a lot of those.

> Where is this claimed?

It's not claimed directly, but this is what the schema offers - type `Comment` has `reactions` field that is just an array of all the reactions that were made to the comment. I'm saying this way of querying is not feasible, so we need to come up with something else

**Comment by zeeshanakram3** [comment]
@kdembler I would start working on suggested changes such as implementing reaction using IDs, multiple reactions support, adding reactions/comments count field to the schema for easy querying.

Answering remaining points here:
> Just to make sure I understand correctly. ReactComment includes only comment_id, that means that comment IDs are globally unique, yes?

Yes.

> If I delete my own comment, would the behaviour be the same as you described above for deletion by moderator? 

Yes, it would have the same behavior. Anyways open to suggestions on how this should be implemented, I mean we could remove comments from DB, but then, in that case would dangling `parentCommentId`s create problems?

> isCommentSectionEnabled seems to be defined for both Channel and Video, I guess it's just a typo

Yes it's typo, I have implemented isCommentSectionEnabled for Channel, the channel owner would use `channel_owner_remark` extrinsic to do that. This would globally enable or disable comments for all for videos.

**Comment by kdembler** [comment]
I think the behaviour for deletion works fine, this way we can easily still show child comments. Although maybe it would make sense to differentiate between comments deleted by users and moderators to show something different in the UI? Maybe `status: VISIBLE | MODERATED | DELETED` or two separate flags `isModerated` and `isDeleted`?

---

On the comment section, I think this should be configurable per video, WDYT?

**Comment by bedeho** [comment]
**I am getting the distinct feeling that there is profound misunderstanding lurking here, at least between me and & Klaud, but possibly also Zeeshan** Should we have call or something to iron this out?

> think what Zeeshan planned is that comments are enabled/disabled on the channel level? 

That would not be the intended behaviour, I am talking about video level comments.

>  Then there would be some custom event required, right? 

You just add it to the video metadata message.

**Comment by kdembler** [comment]
Good idea, let's discuss on call

**Comment by zeeshanakram3** [comment]
> Although maybe it would make sense to differentiate between comments deleted by users and moderators to show something different in the UI?

Good suggestion, I will include this.


@kdembler @bedeho, the comment section being configurable per video is definitely a more customizable solution, however, maybe we can have both options, (configure comment section both for video and channel). e.g. Youtube have both options, 
https://support.google.com/youtube/answer/9482556?hl=en

### How does Youtube manage this?
- Starting off both video and channel (all videos of the channel) comments are enabled.
- Owners can enable/disable comments for any video.
- If you want to disable comments for the channel, then only new videos uploaded on the channel would have the comment section disabled; disabling comments for the channel won't disable comments on the old videos.

**Comment by kdembler** [comment]
I'm not sure if we arrived at conclusion but I would suggest to have comment section enabled/disabled only for specific videos, and we skip channel setting for now

**Comment by bedeho** [comment]
> I'm not sure if we arrived at conclusion but I would suggest to have comment section enabled/disabled only for specific videos, and we skip channel setting for now

💯

**Comment by kdembler** [comment]
@zeeshanakram3 Here are some maybe-not-so-obvious requirements from Atlas:

### Querying

#### Comments list

- We would like to get a paginated list of only top-level comments made under a specific video with a single query
- We would like to sort those comments by newest/oldest but also by most popular (having most reactions, sum of all reactions, doesn't matter which ones)
- We would like to get comments made only by a specific user
- For each comment we would like to know (ideally as part of the single query mentioned above so we don't need a separate request for each comment):
  - Whether it was deleted by the author or moderated by channel
  - Whether it was edited
  - How many of each reaction the comment has
  - Whether the user making the query (can be supplied by argument) has already posted a specific reaction
  - How many replies it has (just a number, doesn't need to apply any filtering)
  - (Nice to have) Data on up to 3 members that have left replies under this comment. This is to enable the UI that can be seen [here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2302%3A264015). Basically so we can show avatars of people who have replied. Ideally, those members are sorted by the number of replies left under this comment. Can be skipped if a lot of work

#### Comment replies

- We would like to get a paginated list of replies under a specific comment with a single query
- For each reply we would like to get the same data as mentioned above

#### Comment history

- If the comment was edited, we would like to get a paginated list of all the edits that were made to this comment, using a single query
- This list should support sorting by most recent edit first
- This list should include the original comment and the most recent version
- For each edit we would like to know when it happened and what was the comment's text after the edit, see relevant design [here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2354%3A194266)

### Actions

- As a user I want to post a comment under a specific video
- As a user I want to post a reply to a specific video
- As a user I want to edit a comment I've posted in the past
- As a user I want to delete a comment I've posted in the past
- As a user I want to add a specific reaction to a specific comment
- As a user I want to remove a specific reaction from a specific comment (assuming I've posted this reaction in the past)
- As a channel owner I want to enable/disable comment section for my video
- As a channel owner I want to moderate (delete) a specific comment under my video

**Comment by kdembler** [comment]
Additional open questions:

How can we handle notifications for comments and reactions. Traditionally those would be handled using queries for low-level blockchain events. Since comments and reactions are a metaprotocol-only feature, those events are not emitted by the blockchain. Maybe query node can simulate those events using metaprotocol messages? Not sure

**Comment by zeeshanakram3** [comment]
> How can we handle notifications for comments and reactions. Traditionally those would be handled using queries for low-level blockchain events. Since comments and reactions are a metaprotocol-only feature, those events are not emitted by the blockchain. Maybe query node can simulate those events using metaprotocol messages? Not sure

Do you mean storing blockchain events in QN state? as prior to metaprotocol events, there has been a query node entity for each blockchain event.

If yes, I have simulated the same for metaprotocol events as well. For example, if `MemberRemarked` event contains `CreatComment` message, then its info would be saved in the `CommentCreatedEvent` entity in the QN state.

**Comment by kdembler** [comment]
Yes, that's what I meant, great to know 💯
